FROM python:3.8
MAINTAINER Frédéric Rodrigo <fred.rodrigo@gmail.com>

RUN mkdir -p /data/work/root/results/

RUN apt update && \
    apt install -y --no-install-recommends \
        bzip2 \
        gettext \
        postgresql-client && \
    apt-get clean

ADD ./requirements.txt /data/project/osmose/frontend/requirements.txt
WORKDIR /data/project/osmose/frontend
RUN pip install uvicorn && pip install -r requirements.txt

ADD . /data/project/osmose/frontend

ENV LANG en_US.UTF-8
CMD uvicorn osmose:app --host 0.0.0.0 --port 20009 --reload --reload-delay 10
EXPOSE 20009
