#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme, Mitja Kleider
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs. If not, see <http://www.gnu.org/licenses/>.
#

import cgi, re, sys, os
root_folder = os.environ["OSMOSE_ROOT"]
sys.path.append(root_folder)
from tools import osmose_common

print "Content-type: text/plain; Charset=UTF-8\n"

form = cgi.FieldStorage()

error_id = form.getfirst("id", "")

(err_source, err_class, err_subclass, err_elems) = error_id.split("-")

err_source = int(err_source)
err_class = int(err_class)
err_subclass = int(err_subclass)

if osmose_common.remove_bug(err_source, err_class, err_subclass, err_elems, "done") == 0:
  print "OK"
else:
  print "FAIL"
