#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme, Mitja Kleider
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs. If not, see <http://www.gnu.org/licenses/>.
#

import cgi, re, sys, os
root_folder = os.environ["OSMOSE_ROOT"]
sys.path.append(root_folder)
from tools import utils

print "Content-type: text/javascript; Charset=UTF-8\n"

form = cgi.FieldStorage()

minlat = int(float(form.getfirst("b", "")) * 1000000)
maxlat = int(float(form.getfirst("t", "")) * 1000000)
minlon = int(float(form.getfirst("l", "")) * 1000000)
maxlon = int(float(form.getfirst("r", "")) * 1000000)

lat = int((minlat + maxlat) / 2)
lon = int((minlon + maxlon) / 2)

items = form.getvalue("item", "").split(",")
items = ",".join([str(int(x)) for x in items if x])

sqlbase  = """
SELECT marker.id,
       marker.item,
       marker.lat,
       marker.lon,
       dynpoi_class.title_fr as title_cur,
       dynpoi_class.title_en as title_def,
       marker.subtitle->'fr' as subtitle_cur,
       marker.subtitle->'en' as subtitle_def
FROM marker
INNER JOIN dynpoi_class
  ON marker.source=dynpoi_class.source AND marker.class=dynpoi_class.class
INNER JOIN dynpoi_update_last
  ON marker.source = dynpoi_update_last.source
WHERE (marker.lat BETWEEN %s AND %s) AND (marker.lon BETWEEN %s and %s) AND """

if items:
    sqlbase += "marker.item IN (%s) AND " % (items)

sqlbase += """
  dynpoi_update_last.timestamp > (now() - interval '3 months')
ORDER BY ABS(lat - %s)+ABS(lon - %s) ASC
LIMIT 100;"""

PgConn    = utils.get_dbconn()
PgCursor  = PgConn.cursor()
PgCursor.execute(sqlbase, (minlat, maxlat, minlon, maxlon, lat, lon))

num = 0
for res in PgCursor.fetchall():
    num += 1
    lat       = float(res["lat"]) / 1000000
    lon       = float(res["lon"]) / 1000000
    error_id  = res["id"]
    title     = res["title_cur"]    or res["title_def"]    or "no title.."
    subtitle  = res["subtitle_cur"] or res["subtitle_def"] or ""
    item      = res["item"] or 0

    text      = title
    if subtitle:
        text += " - <br>" + subtitle
    print "putAJAXMarker('%s', %f, %f, '%s', '%s');" % (error_id, lon, lat, text, item)
